# Generated by Django 5.0.7 on 2024-07-09 18:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anecdotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anecdote',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
